FROM golang:1.22 AS build-stage


WORKDIR /tls-client-api

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /dist/tls-client-api-1.7.5 ./cmd/tls-client-api/main.go

FROM gcr.io/distroless/base-debian11 AS build-release-stage


WORKDIR /

COPY --from=build-stage /dist/tls-client-api-1.7.5 /tls-client-api-1.7.5
COPY ./cmd/tls-client-api/config.dist.yml /config.dist.yml


EXPOSE 8080

USER nonroot:nonroot


ENTRYPOINT ["/tls-client-api-1.7.5"]